config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get :dashboard
      end
      member do
        put :approve
      end
    end
    resources :questions
    resources :topics
  end

  post 'templates/:id' => 'templates#update'

  resources :templates
  resources :interviews do
    resources :interview_questions
  end

  get '*a' => 'static_pages#error'

end

app/controllers/interviews_controller.rb
include ActionView::Helpers::TextHelper

class InterviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_interviewer
  add_breadcrumb "interviews", :interviews_path
  def index
    @interviews = current_user.interviews
    @search = @interviews.search(params[:q] || {})
    @interviews = @search.result.paginate(page: params[:page] || 1, per_page: 6).order(created_at: :desc)
  end

  def new
    @interview = current_user.interviews.new
    add_breadcrumb "new_interview", new_interview_path
  end

  def show
    @interview = current_user.interviews.find(params[:id])
    add_breadcrumb @interview.id, interview_path(@interview)
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Interview does not exist!'
    redirect_to interviews_path
  end

  def create
    @interview = current_user.interviews.create(interview_params)
    @interview.questions.each do |q|
      @interview.interview_questions.create(question_id: q.id)
    end
    @interview_question = @interview.interview_questions.first
    redirect_to edit_interview_interview_question_path(@interview, @interview_question)
  end

  def destroy
    current_user.interviews.find(params[:id]).destroy
    flash[:success] = 'Interview deleted'
    redirect_to interviews_path
  end

  private

  def interview_params
    params.require(:interview).permit(:firstname, :lastname, :target_level, :template_id, :user_id)
  end

  def check_interviewer
    redirect_to authenticated_root_path, notice: 'Access Denied' if current_user.admin?
  end
end

app/helpers/interview_helper.rb
module InterviewHelper
  def bar_color(mark)
    case mark
    when 'green'
      'success'
    when 'yellow'
      'warning'
    when 'red'
      'danger'
    end
  end

  def bar_width(mark)
    case mark
    when 'green'
      '100'
    when 'yellow'
      '75'
    when 'red'
      '50'
    else
      '0'
    end
  end

  def mark_value(mark)
    case mark
    when 'green'
      'EXCELLENT'
    when 'yellow'
      'GOOD'
    when 'red'
      'BAD'
    end
  end

  def mark_color(question_mark, mark)
    color = 'default'
    if question_mark == mark
      color = 'danger' if mark == 'red'
      color = 'warning' if mark == 'yellow'
      color = 'success' if mark == 'green'
    end
    color
  end

  def target_level_param(target_level)
    case target_level
    when 'beginner'
      { level: target_level, width: "40%", color: "success" }
    when 'intermediate'
      { level: target_level, width: "66%", color: "warning" }
    when 'advanced'
      { level: target_level, width: "100%", color: "danger" }
    end
  end

  def interview_color_number(interview)
    number = 'no'
    sum_mark = 0
    sum_question = interview.interview_questions.where('mark IS NOT NULL').count
    interview.interview_questions.each do |question|
      sum_mark += 1 if question.mark == 'yellow'
      sum_mark += 2 if question.mark == 'green'
    end
    number = 10 * sum_mark / sum_question if sum_question > 0
    number
  end

  def interview_color(interview)
    color = 'default'
    if interview_color_number(interview) != 'no'
      color = 'danger'
      color = 'warning' if interview_color_number(interview) >= 5
      color = 'success' if interview_color_number(interview) >= 15
    end
    color
  end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.slim
.form-group
  = form_for @interview, html: { multipart: true } do |f|
    = render 'shared/error_messages', object: f.object
    = f.label :firstaname, "First name"
    = f.text_field :firstname, :placeholder => "First name", class: 'form-control'
    = f.label :lastaname, "Last name"
    = f.text_field :lastname, :placeholder => "Last name", class: 'form-control'
    = f.label 'Target level'
    .form-group
      .btn-group data-toggle="buttons"
        - Interview::TARGET_LEVELS.each do |val|
          - if @interview.target_level == val
            - choosen = "active"
          = f.label :target_level, value: val, class: "btn btn-default radio-label #{choosen}" do
            = f.radio_button :target_level, val, class:"form-radio"
            | #{val}
    = f.label :template_id, "Template"
    = f.collection_select(:template_id, current_user.templates, :id, :name, {:prompt => 'Select a template', :disabled => 'Select a template'}, {class: 'form-control'})
    = f.submit yield(:button_text), class: "btn btn-md btn-success col-md-4 col-md-offset-4"

app/views/interviews/_form_show.html.slim
- @interview.interview_questions.order(id: :asc).each do |question|
  .summary-card id="question#{question.question_id}"
    .progress
      .progress-bar class='progress-bar-#{bar_color("#{question.mark}")}' aria-valuemax="100" role="progressbar" style="width:#{bar_width("#{question.mark}")}%"
    .row
      .col-sm-6
        h4
          | Question: #{@interview.sequence_number(question)}
        .well
          = @interview.questions.find(question.question_id).content
      .col-sm-6
        h4
          | Answer
        .well
          = @interview.questions.find(question.question_id).answer
      .col-sm-12
        h4
          | Comment
        .well
          = question.comment

app/views/interviews/_interview.html.slim
- @interviews.each do |interview|
  tr.info
    td.center
      = link_to interview_path(interview), rel: 'tooltip', title: 'Show interview'
        = interview.id
    td.center
      = link_to interview_path(interview), rel: 'tooltip', title: 'Show interview'
        = render "level", interview: interview
    td
      = link_to template_path(interview.template), rel: 'tooltip', title: 'Show template'
        = interview.template.try(:name)
    td
      = link_to interview_path(interview), rel: 'tooltip', title: 'Show interview'
        | #{interview.firstname} #{interview.lastname}
    td
      = interview.updated_at.localtime.strftime("%m/%d/%Y at %r")
    td  
      = link_to interview_path(interview), rel: 'tooltip', title: 'Show interview', class: "btn btn-sm btn-primary" do
        interview.glyphicon.glyphicon-eye-open   
    td
      = link_to interview_path(interview), method: :delete, data: { confirm: 'Are you sure?' }, rel: 'tooltip', title: 'Delete interview', class: "btn btn-sm btn-danger" do
        interview.glyphicon.glyphicon-remove
    td
      - if interview.interview_questions.where('mark IS NULL').count > 0
        = link_to edit_interview_interview_question_path(interview, interview.not_answered_first_question), rel: 'tooltip', title: 'Finish interview', class: "btn btn-sm btn-#{interview_color(interview)}"
          | #{interview.interview_questions.count}(#{interview.not_answered_questions})
      - else
        = link_to interview_path(interview), rel: 'tooltip', title: 'Interview is finished', class: "btn btn-sm btn-#{interview_color(interview)}"
          | #{interview.interview_questions.count}(#{interview.not_answered_questions})

app/views/interviews/_level.html.slim
- param = target_level_param(interview.target_level)
.progress
  .progress-bar class = "progress-bar-#{param[:color]}" aria-valuemax="100" role="progressbar" style="width:#{param[:width]}"
  	= "#{param[:level]}"

app/views/interviews/_search_form_for.html.slim
form.input-group
  = search_form_for @search, url: interviews_path do |f|
    = f.text_field :firstname_or_lastname_cont, :placeholder => "Search candidate", class: "form-control"
    span.input-group-btn
      = f.submit "Search", class: 'btn btn-default type="button"'

app/views/interviews/index.html.slim
- provide(:title, 'All interviews')
.container.content-area
  h1
    | All interviews
  br
  .row  
    = render 'layouts/messages'
  .row
    = render 'search_form_for'
  .row
    .col-sm-3  
      = link_to 'New interview', new_interview_path, class: 'btn btn-md btn-success'
  br
  .col-sm-12
    .center
      = will_paginate
  - if @interviews.count <= 6
    br     
  .table-responsive#interview-table
    table.table.table-bordered.table-hover
      tr.active
        th.width_3
          h4 Id
        th.width_15
          h4 Target level
        th.width_15
          h4 Template
        th.width_30
          h4 Candidate
        th.width_22
          h4 Date
        th.width_15 colspan="3"
          h4 Action
      = render 'interview'

app/views/interviews/new.html.slim
- provide(:title, 'New interview')
- provide(:button_text, 'Start interview')
.container.content-area
  h1.center
    | New interview
  = render 'form'

app/views/interviews/show.html.slim
- provide(:title, 'Interview')
.container.content-area 
  br
  .dropdown.open id='summary-drop-list'
    button.btn.btn-primary.dropdown-toggle data-toggle="dropdown" type="button" aria-haspopup="true" aria-expanded="true"
      | Questions 
      span.caret
    ul.dropdown-menu.scrollable-list
      - @interview.interview_questions.order(id: :asc).each do |q|
        li
          a href="#question#{q.question_id}" class="btn btn-#{bar_color(q.mark)}"
            = truncate(@interview.questions.find(q.question_id).content, length: 25)
  .row.summary-info
    .col-sm-6
      h3 
        | Interview with 
      h2 
        | #{@interview.firstname} #{@interview.lastname}
    .col-sm-6 
      h3
        | Information: 
      table.table.table-condensed
        tr
          td
            | Date:          
          td
            = @interview.updated_at.localtime.strftime("%m/%d/%Y at %r")
        tr
          td
            | Template:
          td
            = link_to @interview.template.name, template_path(@interview.template)
        tr
          td
            | Target level:          
          td
            = @interview.target_level
  = render 'form_show'