config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get :dashboard
      end
      member do
        put :approve
      end
    end
    resources :questions
    resources :topics
  end

  post 'templates/:id' => 'templates#update'

  resources :templates
  resources :interviews do
    resources :interview_questions
  end

  get '*a' => 'static_pages#error'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :questions
  validates :title, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }
  has_attached_file :image, styles: { thumb: "200x200#" }, convert_options: { thumb: " -gravity center -crop '200x200+0+0'" }, bucket: 'aidinterview-assets', path: "/topics/:id/:filename", s3_protocol: :https, default_url: proc { ActionController::Base.helpers.asset_path('no-image.png') }
  validates_attachment_size :image, less_than: 2.megabytes
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}
end

app/views/templates/_form.html.slim
.form-group
  = form_for @template do |f|
    = render 'shared/error_messages', object: f.object
    h2
      = f.label :name, 'Name:'
    = f.text_area :name, :placeholder => "Write a template name", class: 'form-control input-lg', rows: 2
    h2
      = f.label :template, 'Questions:'
    = f.collection_select :question_ids, Question.all, :id, :content,\
       {:include_blank => false}, {:multiple => true,  class: 'form-control'}
    = f.submit yield(:button_text), class: 'btn btn-md btn-success col-md-4 col-md-offset-4'

app/views/templates/_question_list.html.slim
-unless @template.questions.empty?
  table
    -@template.questions.each do |q|
      tr
        td.name = q.content

app/views/templates/_template.html.slim
tr.info ng-repeat="template in templates | filter:query | orderBy:orderProp"
  td
    a ng-href="/templates/{{template.id}}"
        | {{template.name}}
  td
    a ng-href="/templates/{{template.id}}/edit"
      button class="btn btn-sm btn-primary toleft glyphicon glyphicon-wrench"
    button confirmed-click="removeTemplate(template)" ng-confirm-click="" class="btn btn-sm btn-danger toright glyphicon glyphicon-remove"

app/views/templates/edit.html.slim
- provide(:title, 'Edit template')
.container.content-area ng-app="Template"
  h1.center
    | Edit template
  .form-group ng-controller="TemplateEditCtrl"
    form ng-submit="editTemplate(template)"
      = hidden_field_tag :template_id, @template.id, "ng-model" => "template.id"
      br
      =label_tag :name, 'Name:'
      br
      = text_field_tag :name, nil, placeholder: "Name", required: 'required', \
      class: 'form-control', "ng-model" => "template.name"
      br
      =label_tag :question_id, "Questions"
      br
      = select_tag(:question_ids, options_from_collection_for_select(::Question.all, :id, :content, :question_ids),\
       :multiple => true, :id => "question_ids", class: 'form-control', "ng-model" => "template.question_ids")
      br
      input type="submit" value=("Save changes") class="btn btn-md btn-success col-md-4 col-md-offset-4"

app/views/templates/index.html.slim
- provide(:title, 'All templates')
.container.content-area ng-app="Template"
  h1
    | All templates
  div ng-controller="TemplateCtrl"
    .row
      = render 'layouts/messages'
    .row
      .col-sm-3
        = link_to 'Create new template', new_template_path, class: 'btn btn-md btn-success'
      br
      .col-md-4
        input ng-model="query" placeholder="Search" class='form-control'
      | Sort by:
      select ng-model="orderProp"
        option value="name"
          | Name
    table.table.table-bordered.table-hover
      tr.active
        th.col-sm-4
          h4 Name
        th.col-mdsm-4 colspan="2" width="2%"
          h4 Action
      = render 'template'

app/views/templates/new.html.slim
- provide(:title, 'New template')
.container.content-area ng-app="Template"
  h1.center
    | New template
  .form-group ng-controller="TemplateCtrl"
    form ng-submit="addTemplate()"
      br
      =label_tag :name, 'Name:'
      br
      = text_field_tag :name, nil, placeholder: "Name", required: 'required', \
      class: 'form-control', "ng-model" => "newTemplate.name"
      br
      =label_tag :question_id, "Questions"
      br
      = select_tag(:question_ids, options_from_collection_for_select(::Question.all, :id, :content), prompt: 'Select a question', :multiple => true, :id => "question_ids", class: 'form-control', "ng-model" => "newTemplate.question_ids", required:true)
      br
      input type="submit" value=("Create") class="btn btn-md btn-success col-md-4 col-md-offset-4"

app/views/templates/show.html.slim
- provide(:title, @template.name)
.container.content-area
  h1.center.jumbotron = @template.name
  = render 'layouts/messages'
  h3.jumbotron
    | Number of questions in #{@template.name} template - #{@template.questions.count}
  ul.questions
    -@template.questions.each do |q|
      li = q.content
  p.center
    = link_to edit_template_path(@template), class: "btn btn-sm btn-warning" do
      i.glyphicon.glyphicon-edit Edit