config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get :dashboard
      end
      member do
        put :approve
      end
    end
    resources :questions
    resources :topics
  end

  post 'templates/:id' => 'templates#update'

  resources :templates
  resources :interviews do
    resources :interview_questions
  end

  get '*a' => 'static_pages#error'

end

app/views/layouts/_footer.html.slim
footer.navbar-default.container
  .container
    .row
      .col-lg-12
        ul.list-inline
          li.p.copyright.text-muted.small
            | Copyright © if060-webui-RoR. All Rights Reserved

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top.topnav[role="navigation"]
  .container
    .navbar-header
      a.navbar-brand href="#" Aid-Interview
        
      button.navbar-toggle data-target="#myNavbar" data-toggle="collapse" type="button" 
        span.icon-bar
        span.icon-bar
        span.icon-bar

    #myNavbar.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          - if current_user.admin?
            li
              = link_to('Users', admin_users_path)
            li
              = link_to('Topics', admin_topics_path)
            li
              = link_to('Questions', admin_questions_path)
          - else
            li
              = link_to('Templates', templates_path)
            li
              = link_to('Interviews', interviews_path)

          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | Account
              span.caret
            ul.dropdown-menu
              li
                = link_to('Profile', edit_user_registration_path)
              li.divider
              li
                = link_to('Logout', destroy_user_session_path, :method => :delete)
        - else
          li
            = link_to('Login', new_user_session_path)
 

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  div class=("alert alert-#{key}")
    a.close data-dismiss="alert" href="#"  ×
    ul
      li
        = value

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    title
      = full_title(content_for(:title))
    meta[name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8"]
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    link[href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"]
  body
      = render 'layouts/header'
      - if user_signed_in?
        .container.breadcrumb
          = render_breadcrumbs separator: " > "
      = yield
      = render 'layouts/footer'